### ISSUE TITLE
test command doesn't return failed return code

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-acceptance#13]
the rescue block in the test command does not raise the any errors in the provision or verify phase

**Comment by patrick-wright** [comment]
chef-acceptance use cases

`provision` an environment for a suite
1. Run provision command
2. Upon failure, chef-acceptance should display the chef client run and exception

`verify` against a provisioned environment for a suite
1. Run verify command
2. Upon failure, chef-acceptance should display the chef client run and exception
3. Fail if environment has not been provisioned

`destroy` an environment for a suite
1. Run destroy command
2. Upon failure, chef-acceptance should display the chef client run and exception

`test` a suite (provision, verify, destroy)
1. Run test command
2. Upon provision or verify failure, destroy will run by default and chef-acceptance should display the chef client run and exception
3. Upon provision of verify failure, destroy will not run if --skip-destroy is set and chef-acceptance should display the chef client run and exception
4. Upon destroy failure, chef-acceptance should display the chef client run and exception

**Comment by sersut** [comment]
A few things: 

* I don't think we should store any state information regarding which state we ran before. So I think we can drop (3) under verify command. 
* I think the default behavior should be to not run destroy when something fails. By default I think you would want those VMs to be there for you to investigate. We should change the `--skip-destroy` option to `--force-destroy`. 
* We should be intentional about any failure of execute resource should fail the phase. I.e. we should call out explicitly testing failures in chef-acceptance tests. 

If I was to write this as a card for our board: 

```
As a developer, I would like chef-acceptance to handle and report failures so that I can easily get the information that I seek from CI logs.

h2. Acceptance Criteria

* During a failure, chef-acceptance should report which phase the failure happened, failing suite name (we will need this when we are running suites in parallel), details about the failure if it happened outside the internal Chef Client run (if it is in the Chef Client run, we will already have the output in the logs). 
* During a failure, chef-acceptance should not destroy the VMs unless `--force-destroy` option is passed.
* At the end of the run, chef-acceptance reports how long it took to run the tests.
```
